[tool.poetry]
name = "tele-bot"
version = "0.1.0"
description = ""
authors = ["Woodwine <sd@myexe.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
